services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    # env_file:
    #   - ./env/directus.env
    volumes:
      # - database:/directus/database
      # - uploads:/directus/uploads
      # - extensions:/directus/extensions
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: 'true'
# volumes:
#   database:
#   uploads:
#   extensions:
