version: '3.3'

services:
  nextjs:
    image: node:18
    container_name: nextjs
    working_dir: /app
    restart: always
    networks:
      - proxy_network
    volumes:
      - /opt/docker/stephankugler_dev/client:/app
    environment:
      - NODE_ENV=production
      - STRAPI_URL=http://strapi:1337
    ports:
      - '3000:3000'
    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run build && npm run start"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextjs.rule=Host(`dev.stephankugler.de`)'
      - 'traefik.http.routers.nextjs.entrypoints=websecure'
      - 'traefik.http.routers.nextjs.tls.certresolver=leresolver'

  strapi:
    image: strapi/strapi
    container_name: strapi
    restart: always
    networks:
      - proxy_network
    volumes:
      - ./cms-strapi:/srv/app
    ports:
      - '1337:1337'
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/srv/app/data.db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.strapi.rule=Host(`cms-dev.stephankugler.de`)'
      - 'traefik.http.routers.strapi.entrypoints=websecure'
      - 'traefik.http.routers.strapi.tls.certresolver=leresolver'

networks:
  proxy_network:
    external: true
